// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: proto/cv.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Experience = un poste professionnel
type Experience struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Company       string                 `protobuf:"bytes,1,opt,name=company,proto3" json:"company,omitempty"`
	Position      string                 `protobuf:"bytes,2,opt,name=position,proto3" json:"position,omitempty"`
	StartDate     string                 `protobuf:"bytes,3,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"` // Ex: "Jan 2020"
	EndDate       string                 `protobuf:"bytes,4,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`       // Ex: "Present" ou "Dec 2023"
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Experience) Reset() {
	*x = Experience{}
	mi := &file_proto_cv_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Experience) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Experience) ProtoMessage() {}

func (x *Experience) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cv_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Experience.ProtoReflect.Descriptor instead.
func (*Experience) Descriptor() ([]byte, []int) {
	return file_proto_cv_proto_rawDescGZIP(), []int{0}
}

func (x *Experience) GetCompany() string {
	if x != nil {
		return x.Company
	}
	return ""
}

func (x *Experience) GetPosition() string {
	if x != nil {
		return x.Position
	}
	return ""
}

func (x *Experience) GetStartDate() string {
	if x != nil {
		return x.StartDate
	}
	return ""
}

func (x *Experience) GetEndDate() string {
	if x != nil {
		return x.EndDate
	}
	return ""
}

func (x *Experience) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

// Education = un diplôme ou une formation
type Education struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	School        string                 `protobuf:"bytes,1,opt,name=school,proto3" json:"school,omitempty"`
	Degree        string                 `protobuf:"bytes,2,opt,name=degree,proto3" json:"degree,omitempty"`
	Year          int32                  `protobuf:"varint,3,opt,name=year,proto3" json:"year,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Education) Reset() {
	*x = Education{}
	mi := &file_proto_cv_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Education) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Education) ProtoMessage() {}

func (x *Education) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cv_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Education.ProtoReflect.Descriptor instead.
func (*Education) Descriptor() ([]byte, []int) {
	return file_proto_cv_proto_rawDescGZIP(), []int{1}
}

func (x *Education) GetSchool() string {
	if x != nil {
		return x.School
	}
	return ""
}

func (x *Education) GetDegree() string {
	if x != nil {
		return x.Degree
	}
	return ""
}

func (x *Education) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

// CVRequest = ce que le client envoie au serveur
type CVRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FullName      string                 `protobuf:"bytes,1,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Phone         string                 `protobuf:"bytes,3,opt,name=phone,proto3" json:"phone,omitempty"`
	Location      string                 `protobuf:"bytes,4,opt,name=location,proto3" json:"location,omitempty"`
	Summary       string                 `protobuf:"bytes,5,opt,name=summary,proto3" json:"summary,omitempty"`
	Skills        []string               `protobuf:"bytes,6,rep,name=skills,proto3" json:"skills,omitempty"`           // []string en Go
	Experiences   []*Experience          `protobuf:"bytes,7,rep,name=experiences,proto3" json:"experiences,omitempty"` // []Experience en Go
	Education     []*Education           `protobuf:"bytes,8,rep,name=education,proto3" json:"education,omitempty"`
	Template      string                 `protobuf:"bytes,9,opt,name=template,proto3" json:"template,omitempty"`
	Photo         []byte                 `protobuf:"bytes,10,opt,name=photo,proto3" json:"photo,omitempty"` // "classic" obytes  photo u "modern"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CVRequest) Reset() {
	*x = CVRequest{}
	mi := &file_proto_cv_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CVRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CVRequest) ProtoMessage() {}

func (x *CVRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cv_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CVRequest.ProtoReflect.Descriptor instead.
func (*CVRequest) Descriptor() ([]byte, []int) {
	return file_proto_cv_proto_rawDescGZIP(), []int{2}
}

func (x *CVRequest) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

func (x *CVRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CVRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *CVRequest) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *CVRequest) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *CVRequest) GetSkills() []string {
	if x != nil {
		return x.Skills
	}
	return nil
}

func (x *CVRequest) GetExperiences() []*Experience {
	if x != nil {
		return x.Experiences
	}
	return nil
}

func (x *CVRequest) GetEducation() []*Education {
	if x != nil {
		return x.Education
	}
	return nil
}

func (x *CVRequest) GetTemplate() string {
	if x != nil {
		return x.Template
	}
	return ""
}

func (x *CVRequest) GetPhoto() []byte {
	if x != nil {
		return x.Photo
	}
	return nil
}

// CVResponse = ce que le serveur retourne au client
type CVResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	PdfData       []byte                 `protobuf:"bytes,2,opt,name=pdf_data,json=pdfData,proto3" json:"pdf_data,omitempty"`    // Le PDF en binaire ([]byte en Go)
	Filename      string                 `protobuf:"bytes,3,opt,name=filename,proto3" json:"filename,omitempty"`                 // Ex: "abraham-kouassi-cv.pdf"
	ErrorMsg      string                 `protobuf:"bytes,4,opt,name=error_msg,json=errorMsg,proto3" json:"error_msg,omitempty"` // Message d'erreur si success = false
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CVResponse) Reset() {
	*x = CVResponse{}
	mi := &file_proto_cv_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CVResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CVResponse) ProtoMessage() {}

func (x *CVResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cv_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CVResponse.ProtoReflect.Descriptor instead.
func (*CVResponse) Descriptor() ([]byte, []int) {
	return file_proto_cv_proto_rawDescGZIP(), []int{3}
}

func (x *CVResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CVResponse) GetPdfData() []byte {
	if x != nil {
		return x.PdfData
	}
	return nil
}

func (x *CVResponse) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *CVResponse) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

// ProgressEvent = un événement de progression (pour le streaming)
type ProgressEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Step          string                 `protobuf:"bytes,1,opt,name=step,proto3" json:"step,omitempty"`                      // Ex: "Génération du PDF..."
	Percent       int32                  `protobuf:"varint,2,opt,name=percent,proto3" json:"percent,omitempty"`               // 0 à 100
	Done          bool                   `protobuf:"varint,3,opt,name=done,proto3" json:"done,omitempty"`                     // true = terminé
	PdfData       []byte                 `protobuf:"bytes,4,opt,name=pdf_data,json=pdfData,proto3" json:"pdf_data,omitempty"` // Rempli uniquement quand done = true
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProgressEvent) Reset() {
	*x = ProgressEvent{}
	mi := &file_proto_cv_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProgressEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProgressEvent) ProtoMessage() {}

func (x *ProgressEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cv_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProgressEvent.ProtoReflect.Descriptor instead.
func (*ProgressEvent) Descriptor() ([]byte, []int) {
	return file_proto_cv_proto_rawDescGZIP(), []int{4}
}

func (x *ProgressEvent) GetStep() string {
	if x != nil {
		return x.Step
	}
	return ""
}

func (x *ProgressEvent) GetPercent() int32 {
	if x != nil {
		return x.Percent
	}
	return 0
}

func (x *ProgressEvent) GetDone() bool {
	if x != nil {
		return x.Done
	}
	return false
}

func (x *ProgressEvent) GetPdfData() []byte {
	if x != nil {
		return x.PdfData
	}
	return nil
}

var File_proto_cv_proto protoreflect.FileDescriptor

const file_proto_cv_proto_rawDesc = "" +
	"\n" +
	"\x0eproto/cv.proto\x12\x02cv\"\x9e\x01\n" +
	"\n" +
	"Experience\x12\x18\n" +
	"\acompany\x18\x01 \x01(\tR\acompany\x12\x1a\n" +
	"\bposition\x18\x02 \x01(\tR\bposition\x12\x1d\n" +
	"\n" +
	"start_date\x18\x03 \x01(\tR\tstartDate\x12\x19\n" +
	"\bend_date\x18\x04 \x01(\tR\aendDate\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\"O\n" +
	"\tEducation\x12\x16\n" +
	"\x06school\x18\x01 \x01(\tR\x06school\x12\x16\n" +
	"\x06degree\x18\x02 \x01(\tR\x06degree\x12\x12\n" +
	"\x04year\x18\x03 \x01(\x05R\x04year\"\xb3\x02\n" +
	"\tCVRequest\x12\x1b\n" +
	"\tfull_name\x18\x01 \x01(\tR\bfullName\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x14\n" +
	"\x05phone\x18\x03 \x01(\tR\x05phone\x12\x1a\n" +
	"\blocation\x18\x04 \x01(\tR\blocation\x12\x18\n" +
	"\asummary\x18\x05 \x01(\tR\asummary\x12\x16\n" +
	"\x06skills\x18\x06 \x03(\tR\x06skills\x120\n" +
	"\vexperiences\x18\a \x03(\v2\x0e.cv.ExperienceR\vexperiences\x12+\n" +
	"\teducation\x18\b \x03(\v2\r.cv.EducationR\teducation\x12\x1a\n" +
	"\btemplate\x18\t \x01(\tR\btemplate\x12\x14\n" +
	"\x05photo\x18\n" +
	" \x01(\fR\x05photo\"z\n" +
	"\n" +
	"CVResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x19\n" +
	"\bpdf_data\x18\x02 \x01(\fR\apdfData\x12\x1a\n" +
	"\bfilename\x18\x03 \x01(\tR\bfilename\x12\x1b\n" +
	"\terror_msg\x18\x04 \x01(\tR\berrorMsg\"l\n" +
	"\rProgressEvent\x12\x12\n" +
	"\x04step\x18\x01 \x01(\tR\x04step\x12\x18\n" +
	"\apercent\x18\x02 \x01(\x05R\apercent\x12\x12\n" +
	"\x04done\x18\x03 \x01(\bR\x04done\x12\x19\n" +
	"\bpdf_data\x18\x04 \x01(\fR\apdfData2p\n" +
	"\vCVGenerator\x12+\n" +
	"\n" +
	"GenerateCV\x12\r.cv.CVRequest\x1a\x0e.cv.CVResponse\x124\n" +
	"\x0eStreamProgress\x12\r.cv.CVRequest\x1a\x11.cv.ProgressEvent0\x01B.Z,github.com/dacostaabraham/cv-generator/protob\x06proto3"

var (
	file_proto_cv_proto_rawDescOnce sync.Once
	file_proto_cv_proto_rawDescData []byte
)

func file_proto_cv_proto_rawDescGZIP() []byte {
	file_proto_cv_proto_rawDescOnce.Do(func() {
		file_proto_cv_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_cv_proto_rawDesc), len(file_proto_cv_proto_rawDesc)))
	})
	return file_proto_cv_proto_rawDescData
}

var file_proto_cv_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_cv_proto_goTypes = []any{
	(*Experience)(nil),    // 0: cv.Experience
	(*Education)(nil),     // 1: cv.Education
	(*CVRequest)(nil),     // 2: cv.CVRequest
	(*CVResponse)(nil),    // 3: cv.CVResponse
	(*ProgressEvent)(nil), // 4: cv.ProgressEvent
}
var file_proto_cv_proto_depIdxs = []int32{
	0, // 0: cv.CVRequest.experiences:type_name -> cv.Experience
	1, // 1: cv.CVRequest.education:type_name -> cv.Education
	2, // 2: cv.CVGenerator.GenerateCV:input_type -> cv.CVRequest
	2, // 3: cv.CVGenerator.StreamProgress:input_type -> cv.CVRequest
	3, // 4: cv.CVGenerator.GenerateCV:output_type -> cv.CVResponse
	4, // 5: cv.CVGenerator.StreamProgress:output_type -> cv.ProgressEvent
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_cv_proto_init() }
func file_proto_cv_proto_init() {
	if File_proto_cv_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_cv_proto_rawDesc), len(file_proto_cv_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_cv_proto_goTypes,
		DependencyIndexes: file_proto_cv_proto_depIdxs,
		MessageInfos:      file_proto_cv_proto_msgTypes,
	}.Build()
	File_proto_cv_proto = out.File
	file_proto_cv_proto_goTypes = nil
	file_proto_cv_proto_depIdxs = nil
}
