// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.0
// source: proto/cv.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CVGenerator_GenerateCV_FullMethodName     = "/cv.CVGenerator/GenerateCV"
	CVGenerator_StreamProgress_FullMethodName = "/cv.CVGenerator/StreamProgress"
)

// CVGeneratorClient is the client API for CVGenerator service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CVGeneratorClient interface {
	// GenerateCV : Unary — 1 requête → 1 réponse avec le PDF complet
	GenerateCV(ctx context.Context, in *CVRequest, opts ...grpc.CallOption) (*CVResponse, error)
	// StreamProgress : Server Streaming — 1 requête → N événements de progression
	// Le client reçoit des updates en temps réel pendant la génération
	StreamProgress(ctx context.Context, in *CVRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ProgressEvent], error)
}

type cVGeneratorClient struct {
	cc grpc.ClientConnInterface
}

func NewCVGeneratorClient(cc grpc.ClientConnInterface) CVGeneratorClient {
	return &cVGeneratorClient{cc}
}

func (c *cVGeneratorClient) GenerateCV(ctx context.Context, in *CVRequest, opts ...grpc.CallOption) (*CVResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CVResponse)
	err := c.cc.Invoke(ctx, CVGenerator_GenerateCV_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cVGeneratorClient) StreamProgress(ctx context.Context, in *CVRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ProgressEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &CVGenerator_ServiceDesc.Streams[0], CVGenerator_StreamProgress_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[CVRequest, ProgressEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CVGenerator_StreamProgressClient = grpc.ServerStreamingClient[ProgressEvent]

// CVGeneratorServer is the server API for CVGenerator service.
// All implementations must embed UnimplementedCVGeneratorServer
// for forward compatibility.
type CVGeneratorServer interface {
	// GenerateCV : Unary — 1 requête → 1 réponse avec le PDF complet
	GenerateCV(context.Context, *CVRequest) (*CVResponse, error)
	// StreamProgress : Server Streaming — 1 requête → N événements de progression
	// Le client reçoit des updates en temps réel pendant la génération
	StreamProgress(*CVRequest, grpc.ServerStreamingServer[ProgressEvent]) error
	mustEmbedUnimplementedCVGeneratorServer()
}

// UnimplementedCVGeneratorServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCVGeneratorServer struct{}

func (UnimplementedCVGeneratorServer) GenerateCV(context.Context, *CVRequest) (*CVResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GenerateCV not implemented")
}
func (UnimplementedCVGeneratorServer) StreamProgress(*CVRequest, grpc.ServerStreamingServer[ProgressEvent]) error {
	return status.Error(codes.Unimplemented, "method StreamProgress not implemented")
}
func (UnimplementedCVGeneratorServer) mustEmbedUnimplementedCVGeneratorServer() {}
func (UnimplementedCVGeneratorServer) testEmbeddedByValue()                     {}

// UnsafeCVGeneratorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CVGeneratorServer will
// result in compilation errors.
type UnsafeCVGeneratorServer interface {
	mustEmbedUnimplementedCVGeneratorServer()
}

func RegisterCVGeneratorServer(s grpc.ServiceRegistrar, srv CVGeneratorServer) {
	// If the following call panics, it indicates UnimplementedCVGeneratorServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CVGenerator_ServiceDesc, srv)
}

func _CVGenerator_GenerateCV_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CVRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CVGeneratorServer).GenerateCV(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CVGenerator_GenerateCV_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CVGeneratorServer).GenerateCV(ctx, req.(*CVRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CVGenerator_StreamProgress_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(CVRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CVGeneratorServer).StreamProgress(m, &grpc.GenericServerStream[CVRequest, ProgressEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CVGenerator_StreamProgressServer = grpc.ServerStreamingServer[ProgressEvent]

// CVGenerator_ServiceDesc is the grpc.ServiceDesc for CVGenerator service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CVGenerator_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cv.CVGenerator",
	HandlerType: (*CVGeneratorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GenerateCV",
			Handler:    _CVGenerator_GenerateCV_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamProgress",
			Handler:       _CVGenerator_StreamProgress_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/cv.proto",
}
